/**
 * Mock users — schema-shaped.
 *
 * REPLACE WITH: a `users` table query against Postgres via Drizzle.
 * The shape returned by the query should match `User` in `lib/types.ts`.
 *
 * profileImageUrl is null in the sandbox — the <Avatar> component falls back
 * to initials-in-colored-circle until real uploads exist.
 *
 * `discipline` is the one-line self-identification rendered as a tag below
 * the name on every profile. `profileMode` controls /u/[handle] rendering:
 * "contributor" is the cooperative profile (default), "epk" flips to the
 * Electronic Press Kit shell for artists. EPK rendering also requires a
 * matching `ArtistEpk` row in `mock-data/artist-epk.ts`.
 */
import type { User } from "@/lib/types";

export const MOCK_USERS: User[] = [
  {
    id: "u_jamar",
    email: "properpreparationism@gmail.com",
    handle: "jamar",
    firstName: "Jamar",
    lastName: "McCarthy",
    profileImageUrl: null,
    membershipTier: "member",
    primaryIndustry: "creative-media",
    secondaryIndustries: ["professional-services"],
    dataParticipation: false,
    skills: ["product strategy", "brand", "narrative", "ops"],
    discipline: "Cooperative Builder, Strategist",
    profileMode: "contributor",
    bio: "Future Modern Builderberg LLC. Building the cooperative.",
    portfolioUrl: "https://afuturemodern.com",
    buildTokenBalance: "12500.00000000",
    isAdmin: true,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000001",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: "acct_1Q9futuremodern0001",
    stripePayoutsEnabled: true,
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2026-05-04T00:00:00Z",
  },
  {
    id: "u_chibu",
    email: "chibu@example.com",
    handle: "chibu",
    firstName: "Chibu",
    lastName: "—",
    profileImageUrl: null,
    // Member tier preserved on paper while arbitration is unresolved.
    // Defensive posture: don't tear up structural standing in a way
    // that could be used against the cooperative; instead gate
    // discovery via the `profilePublic` flag below. See key-people.md.
    membershipTier: "member",
    primaryIndustry: "stem",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["full-stack", "smart contracts", "infra"],
    discipline: "Full-stack Engineer",
    profileMode: "contributor",
    bio: "Core contributor.",
    portfolioUrl: null,
    buildTokenBalance: "8200.50000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    // Profile excluded from public discovery surfaces (showcase, member
    // directories, homepage rails, search index) pending arbitration
    // resolution. Direct-link URL still resolves but stays out of
    // crawler indexes via the existing visibility predicate.
    profilePublic: false,
    walletAddress: "0x6551000000000000000000000000000000000002",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: "acct_1Q9chibu0002",
    stripePayoutsEnabled: true,
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
  },
  {
    id: "u_aliza",
    email: "aliza@example.com",
    handle: "aliza",
    firstName: "Aliza",
    lastName: "—",
    profileImageUrl: null,
    membershipTier: "partner",
    primaryIndustry: "creative-media",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["direction", "video", "editing"],
    discipline: "Creative Director, Editor",
    profileMode: "contributor",
    bio: "Creative direction + post-production.",
    portfolioUrl: null,
    buildTokenBalance: "3450.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000003",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: "acct_1Q9aliza0003",
    stripePayoutsEnabled: false,
    createdAt: "2025-03-12T00:00:00Z",
    updatedAt: "2026-03-29T00:00:00Z",
  },
  {
    id: "u_michael",
    email: "michael@example.com",
    handle: "michael",
    firstName: "Michael",
    lastName: "—",
    profileImageUrl: null,
    membershipTier: "partner",
    primaryIndustry: "professional-services",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["consulting", "ops", "finance"],
    discipline: "Strategy + Ops",
    profileMode: "contributor",
    bio: "Professional services lead.",
    portfolioUrl: null,
    buildTokenBalance: "5100.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000004",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: "acct_1Q9michael0004",
    stripePayoutsEnabled: true,
    createdAt: "2025-04-02T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "u_trevor",
    email: "trevor@example.com",
    handle: "trevor",
    firstName: "Trevor",
    lastName: "—",
    profileImageUrl: null,
    membershipTier: "prospect",
    primaryIndustry: "stem",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["data", "ML"],
    discipline: "AI Engineer",
    profileMode: "contributor",
    bio: "Applying for partner tier.",
    portfolioUrl: null,
    buildTokenBalance: "0.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: null,
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: null,
    stripePayoutsEnabled: false,
    createdAt: "2026-02-14T00:00:00Z",
    updatedAt: "2026-04-18T00:00:00Z",
  },
  {
    id: "u_rob",
    email: "rob@example.com",
    handle: "rob",
    firstName: "Rob",
    lastName: "Turley",
    profileImageUrl: null,
    membershipTier: "partner",
    primaryIndustry: "professional-services",
    secondaryIndustries: ["creative-media"],
    dataParticipation: false,
    skills: ["growth", "go-to-market", "sales"],
    discipline: "RevOps Specialist",
    profileMode: "contributor",
    bio: "RevOps Hitman Consulting. Activated channel partner.",
    portfolioUrl: null,
    buildTokenBalance: "2750.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000005",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: "acct_1Q9rob0005",
    stripePayoutsEnabled: true,
    createdAt: "2025-05-20T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },

  // ── Initial EPK cohort (artists) — September launch.
  // EPK content for each lives in mock-data/artist-epk.ts.
  {
    id: "u_bbg",
    email: "bbg@example.com",
    handle: "bbg",
    firstName: "Big Baby",
    lastName: "Gandhi",
    profileImageUrl: null,
    membershipTier: "member",
    primaryIndustry: "creative-media",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["lyricism", "production", "creative direction"],
    discipline: "Rapper, Producer",
    profileMode: "epk",
    bio: "Head of Creative Strategy at Future Modern.",
    portfolioUrl: null,
    buildTokenBalance: "9100.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000010",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: null,
    stripePayoutsEnabled: false,
    createdAt: "2022-08-01T00:00:00Z",
    updatedAt: "2026-05-04T00:00:00Z",
  },
  {
    id: "u_sahtyre",
    email: "sahtyre@example.com",
    handle: "sahtyre",
    firstName: "Sahtyre",
    lastName: null,
    profileImageUrl: null,
    membershipTier: "member",
    primaryIndustry: "creative-media",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["lyricism", "production"],
    discipline: "Rapper",
    profileMode: "epk",
    bio: "Long-time Future Modern collaborator. Catalog series exclusive 'STILL HIGH'.",
    portfolioUrl: null,
    buildTokenBalance: "4200.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000011",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: null,
    stripePayoutsEnabled: false,
    createdAt: "2022-10-25T00:00:00Z",
    updatedAt: "2026-05-04T00:00:00Z",
  },
  {
    id: "u_jrusalam",
    email: "jrusalam@gmail.com",
    handle: "jrusalam",
    firstName: "Jrusalam",
    lastName: null,
    profileImageUrl: null,
    membershipTier: "member",
    primaryIndustry: "creative-media",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["lyricism", "performance"],
    discipline: "Hip Hop Artist · Parable Rap",
    profileMode: "epk",
    bio: "Raleigh native, born from the cypher at the NCSU Free Expression Tunnel. Parable Rap.",
    portfolioUrl: "https://jrusalam.com",
    buildTokenBalance: "1500.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000012",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: null,
    stripePayoutsEnabled: false,
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2026-05-04T00:00:00Z",
  },
  {
    id: "u_keyboard_kid",
    email: "keyboardkid@example.com",
    handle: "keyboardkid",
    firstName: "Keyboard",
    lastName: "Kid",
    profileImageUrl: null,
    membershipTier: "member",
    primaryIndustry: "creative-media",
    secondaryIndustries: [],
    dataParticipation: false,
    skills: ["production", "lyricism"],
    discipline: "Producer, Rapper",
    profileMode: "epk",
    bio: "BasedWorld. First-ever BasedWorld NFT through the Catalog inaugural release campaign.",
    portfolioUrl: null,
    buildTokenBalance: "3800.00000000",
    isAdmin: false,
    talentTags: [],
    avatarPortraitUrl: null,
    profilePublic: true,
    walletAddress: "0x6551000000000000000000000000000000000013",
    connectedWalletAddress: null,
    connectedWalletProvider: null,
    walletConnectedAt: null,
    stripeAccountId: null,
    stripePayoutsEnabled: false,
    createdAt: "2022-09-01T00:00:00Z",
    updatedAt: "2026-05-04T00:00:00Z",
  },
];
